// Cloudflare Worker entry: the OpenNext app plus a Cron Trigger that drains
// background jobs (CRM delivery retries, outbound channel messages, knowledge
// indexing). Without it, jobs that were not finished right after their request
// waited until some later request happened to drain the queue.
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

type Env = { PUBLIC_APP_URL?: string; CRON_SECRET?: string };
type Ctx = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: handler.fetch,
  async scheduled(_controller: unknown, env: Env, ctx: Ctx) {
    // The request never leaves this isolate. When CRON_SECRET is not configured,
    // a one-time token shared through the isolate's global scope authorizes it.
    const token = crypto.randomUUID();
    (globalThis as { __lemiriCronToken?: string }).__lemiriCronToken = token;
    const origin = env.PUBLIC_APP_URL || "https://lemeriai.com";
    const request = new Request(`${origin}/api/internal/jobs/run`, {
      method: "POST",
      headers: env.CRON_SECRET ? { authorization: `Bearer ${env.CRON_SECRET}` } : { "x-lemiri-cron": token },
    });
    ctx.waitUntil(Promise.resolve(handler.fetch(request, env, ctx)).finally(() => {
      delete (globalThis as { __lemiriCronToken?: string }).__lemiriCronToken;
    }));
  },
};

// @ts-ignore -- Durable Object classes declared by the OpenNext build
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
