import { z } from "zod";
import { db } from "@/lib/db";
import { enqueueCrmEvent } from "@/lib/integrations/queue";
import type { AIAction } from "./types";
import { getWorkspaceTranslator } from "@/lib/workspace-locale";

const contactFields={name:z.string().trim().min(2).max(120).optional(),phone:z.string().trim().min(5).max(40).regex(/^[+\d\s()-]+$/).optional(),email:z.string().trim().toLowerCase().email().max(200).optional()};
// Contact details the AI collected in the conversation are written to the CRM customer.
async function updateCustomerContact(customerId:string,input:{name?:string;phone?:string;email?:string}){const data=Object.fromEntries(Object.entries({name:input.name,phone:input.phone,email:input.email}).filter(([,value])=>value));if(Object.keys(data).length)return db.customer.update({where:{id:customerId},data});return db.customer.findUniqueOrThrow({where:{id:customerId}})}
async function conversationCustomer(ctx:{workspaceId:string;conversationId?:string}){if(!ctx.conversationId)throw new Error("Conversation is required");const conversation=await db.conversation.findFirst({where:{id:ctx.conversationId,workspaceId:ctx.workspaceId},include:{customer:true}});if(!conversation)throw new Error("Conversation not found");return conversation}
const createLead:AIAction={key:"createLead",name:"Создавать лиды",description:"Создаёт лид для клиента текущего диалога",schema:z.object({interest:z.string().min(2).max(200),stage:z.enum(["NEW","QUALIFIED"]).default("NEW"),...contactFields}),async execute(ctx,input){const conversation=await conversationCustomer(ctx);const customer=await updateCustomerContact(conversation.customerId,input);const lead=await db.lead.create({data:{workspaceId:ctx.workspaceId,customerId:conversation.customerId,interest:input.interest,stage:input.stage}});await db.analyticsEvent.create({data:{workspaceId:ctx.workspaceId,type:"LEAD_CREATED",payload:{leadId:lead.id,source:"AI_ACTION",channelType:conversation.channelType}}});const {t}=await getWorkspaceTranslator(ctx.workspaceId);await db.notification.create({data:{workspaceId:ctx.workspaceId,type:"LEAD",title:t("server.newLeadTitle",{name:customer.name}).slice(0,120),body:[input.interest,customer.phone,customer.email].filter(Boolean).join(" · ").slice(0,1000)}});await enqueueCrmEvent(ctx.workspaceId,"lead.created",{...lead,customer});return lead}};
const MIN_APPOINTMENT_GAP_MS=30*60_000;
function localParts(date:Date,timezone:string){const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:timezone,weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date).map(part=>[part.type,part.value]));return{day:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(parts.weekday),time:`${parts.hour}:${parts.minute}`}}
const createAppointment:AIAction={key:"createAppointment",name:"Создавать записи",description:"Создаёт запись после подтверждения времени клиентом",schema:z.object({service:z.string().min(2).max(160),startsAt:z.coerce.date().refine(value=>value.getTime()>Date.now()),...contactFields}),async execute(ctx,input){const conversation=await conversationCustomer(ctx);
  // Respect the workspace calendar: working days/hours and no double booking.
  const settings=await db.workspaceSettings.findUnique({where:{workspaceId:ctx.workspaceId},select:{timezone:true,workingHours:true}});const hours=(settings?.workingHours as {days?:number[];start?:string;end?:string}|null)??{days:[1,2,3,4,5],start:"09:00",end:"18:00"};let slot={day:input.startsAt.getUTCDay(),time:input.startsAt.toISOString().slice(11,16)};try{slot=localParts(input.startsAt,settings?.timezone??"Europe/Moscow")}catch{}
  if((hours.days?.length&&!hours.days.includes(slot.day))||(hours.start&&slot.time<hours.start)||(hours.end&&slot.time>=hours.end))throw new Error("OUTSIDE_WORKING_HOURS");
  const clash=await db.appointment.findFirst({where:{workspaceId:ctx.workspaceId,status:{in:["SCHEDULED","CONFIRMED"]},startsAt:{gt:new Date(input.startsAt.getTime()-MIN_APPOINTMENT_GAP_MS),lt:new Date(input.startsAt.getTime()+MIN_APPOINTMENT_GAP_MS)}},select:{id:true}});if(clash)throw new Error("SLOT_TAKEN");
  const customer=await updateCustomerContact(conversation.customerId,input);const appointment=await db.appointment.create({data:{workspaceId:ctx.workspaceId,customerId:conversation.customerId,service:input.service,startsAt:input.startsAt,status:"SCHEDULED"}});await db.analyticsEvent.create({data:{workspaceId:ctx.workspaceId,type:"APPOINTMENT_CREATED",payload:{appointmentId:appointment.id,source:"AI_ACTION",channelType:conversation.channelType}}});const {t}=await getWorkspaceTranslator(ctx.workspaceId);await db.notification.create({data:{workspaceId:ctx.workspaceId,type:"APPOINTMENT",title:t("server.newAppointmentTitle",{name:customer.name}).slice(0,120),body:`${input.service} · ${input.startsAt.toISOString()}`.slice(0,1000)}});await enqueueCrmEvent(ctx.workspaceId,"appointment.created",{...appointment,customer});return appointment}};
const notifyManager:AIAction={key:"notifyManager",name:"Уведомлять менеджера",description:"Создаёт уведомление для команды",schema:z.object({title:z.string().min(2).max(120),body:z.string().min(2).max(1000)}),async execute(ctx,input){return db.notification.create({data:{workspaceId:ctx.workspaceId,type:"AI_ACTION",title:input.title,body:input.body}})}};
const handoffToHuman:AIAction={key:"handoffToHuman",name:"Передавать человеку",description:"Останавливает AI и передаёт диалог менеджеру",schema:z.object({reason:z.string().min(2).max(500),summary:z.string().min(2).max(1000)}),async execute(ctx,input){if(!ctx.conversationId)throw new Error("Conversation is required");const conversation=await db.conversation.findFirst({where:{id:ctx.conversationId,workspaceId:ctx.workspaceId}});if(!conversation)throw new Error("Conversation not found");return db.$transaction([db.humanHandoff.create({data:{conversationId:conversation.id,reason:input.reason,summary:input.summary,status:"OPEN"}}),db.conversation.update({where:{id:conversation.id},data:{status:"NEEDS_ATTENTION"}}),db.analyticsEvent.create({data:{workspaceId:ctx.workspaceId,type:"HANDOFF_CREATED",payload:{conversationId:conversation.id,source:"AI_ACTION",reason:input.reason}}})])}};
const registry=new Map<string,AIAction>([createLead,createAppointment,notifyManager,handoffToHuman].map(action=>[action.key,action]));
export const actionCatalog=[...registry.values()];
export function getAction(key:string){const action=registry.get(key);if(!action)throw new Error(`Unknown action: ${key}`);return action}
export async function ensureActionDefinitions(){for(const action of actionCatalog)await db.actionDefinition.upsert({where:{key:action.key},create:{key:action.key,name:action.name,description:action.description,inputSchema:{type:"object"}},update:{name:action.name,description:action.description}})}
