import { z } from "zod";
import { db } from "@/lib/db";
import { enqueueCrmEvent } from "@/lib/integrations/queue";
import type { AIAction } from "./types";

const createLead:AIAction={key:"createLead",name:"Создавать лиды",description:"Создаёт лид для клиента текущего диалога",schema:z.object({interest:z.string().min(2).max(200),stage:z.enum(["NEW","QUALIFIED"]).default("NEW")}),async execute(ctx,input){if(!ctx.conversationId)throw new Error("Conversation is required");const conversation=await db.conversation.findFirst({where:{id:ctx.conversationId,workspaceId:ctx.workspaceId},include:{customer:true}});if(!conversation)throw new Error("Conversation not found");const lead=await db.lead.create({data:{workspaceId:ctx.workspaceId,customerId:conversation.customerId,interest:input.interest,stage:input.stage}});await db.analyticsEvent.create({data:{workspaceId:ctx.workspaceId,type:"LEAD_CREATED",payload:{leadId:lead.id,source:"AI_ACTION"}}});await enqueueCrmEvent(ctx.workspaceId,"lead.created",{...lead,customer:conversation.customer});return lead}};
const createAppointment:AIAction={key:"createAppointment",name:"Создавать записи",description:"Создаёт запись после подтверждения времени клиентом",schema:z.object({service:z.string().min(2).max(160),startsAt:z.coerce.date().refine(value=>value.getTime()>Date.now())}),async execute(ctx,input){if(!ctx.conversationId)throw new Error("Conversation is required");const conversation=await db.conversation.findFirst({where:{id:ctx.conversationId,workspaceId:ctx.workspaceId},include:{customer:true}});if(!conversation)throw new Error("Conversation not found");const appointment=await db.appointment.create({data:{workspaceId:ctx.workspaceId,customerId:conversation.customerId,service:input.service,startsAt:input.startsAt,status:"SCHEDULED"}});await db.analyticsEvent.create({data:{workspaceId:ctx.workspaceId,type:"APPOINTMENT_CREATED",payload:{appointmentId:appointment.id,source:"AI_ACTION"}}});await enqueueCrmEvent(ctx.workspaceId,"appointment.created",{...appointment,customer:conversation.customer});return appointment}};
const notifyManager:AIAction={key:"notifyManager",name:"Уведомлять менеджера",description:"Создаёт уведомление для команды",schema:z.object({title:z.string().min(2).max(120),body:z.string().min(2).max(1000)}),async execute(ctx,input){return db.notification.create({data:{workspaceId:ctx.workspaceId,type:"AI_ACTION",title:input.title,body:input.body}})}};
const handoffToHuman:AIAction={key:"handoffToHuman",name:"Передавать человеку",description:"Останавливает AI и передаёт диалог менеджеру",schema:z.object({reason:z.string().min(2).max(500),summary:z.string().min(2).max(1000)}),async execute(ctx,input){if(!ctx.conversationId)throw new Error("Conversation is required");const conversation=await db.conversation.findFirst({where:{id:ctx.conversationId,workspaceId:ctx.workspaceId}});if(!conversation)throw new Error("Conversation not found");return db.$transaction([db.humanHandoff.create({data:{conversationId:conversation.id,reason:input.reason,summary:input.summary,status:"OPEN"}}),db.conversation.update({where:{id:conversation.id},data:{status:"NEEDS_ATTENTION"}}),db.analyticsEvent.create({data:{workspaceId:ctx.workspaceId,type:"HANDOFF_CREATED",payload:{conversationId:conversation.id,source:"AI_ACTION",reason:input.reason}}})])}};
const registry=new Map<string,AIAction>([createLead,createAppointment,notifyManager,handoffToHuman].map(action=>[action.key,action]));
export const actionCatalog=[...registry.values()];
export function getAction(key:string){const action=registry.get(key);if(!action)throw new Error(`Unknown action: ${key}`);return action}
export async function ensureActionDefinitions(){for(const action of actionCatalog)await db.actionDefinition.upsert({where:{key:action.key},create:{key:action.key,name:action.name,description:action.description,inputSchema:{type:"object"}},update:{name:action.name,description:action.description}})}
