import assert from "node:assert/strict";
import test from "node:test";
import { OpenAIEmbeddingProvider } from "../src/lib/ai/embeddings.ts";
import { OpenAIProvider, responseOutputText } from "../src/lib/ai/providers/openai.ts";

test("extracts output text from Responses API",()=>{assert.equal(responseOutputText({output:[{type:"message",content:[{type:"output_text",text:"ok"}]}]}),"ok")});
test("OpenAI provider validates citations against retrieved chunks",async()=>{const fetcher=async()=>new Response(JSON.stringify({output:[{type:"message",content:[{type:"output_text",text:JSON.stringify({text:"Стоимость 3000",confidence:.9,usedSourceIds:["chunk-1"],handoffReason:null,actionRequest:null})}]}]}),{status:200});const provider=new OpenAIProvider("test","test-model",fetcher as typeof fetch);const result=await provider.generateResponse({employeeName:"Lemiri",role:"sales",goal:"help",tone:"warm",messages:[{role:"user",content:"price?"}],knowledge:[{id:"chunk-1",content:"Стоимость 3000",sourceLabel:"Price",score:.9}]});assert.deepEqual(result.usedSourceIds,["chunk-1"]);assert.equal(result.confidence,.9)});
test("OpenAI provider accepts only explicitly allowed action requests",async()=>{const payload={text:"Оформляю запись",confidence:.95,usedSourceIds:[],handoffReason:null,actionRequest:{key:"createAppointment",input:{interest:null,stage:null,service:"Консультация",startsAt:"2030-01-01T10:00:00Z",title:null,body:null,reason:null,summary:null}}};const fetcher=async()=>new Response(JSON.stringify({output:[{type:"message",content:[{type:"output_text",text:JSON.stringify(payload)}]}]}),{status:200});const provider=new OpenAIProvider("test","test-model",fetcher as typeof fetch);const result=await provider.generateResponse({employeeName:"Lemiri",role:"sales",goal:"help",tone:"warm",messages:[{role:"user",content:"Запишите меня"}],knowledge:[],allowedActionKeys:["createAppointment"]});assert.deepEqual(result.actionRequest,{key:"createAppointment",input:{service:"Консультация",startsAt:"2030-01-01T10:00:00Z"}})});
test("embeddings preserve API index order",async()=>{const fetcher=async()=>new Response(JSON.stringify({data:[{index:1,embedding:[3,4]},{index:0,embedding:[1,2]}]}),{status:200});const provider=new OpenAIEmbeddingProvider("test","embed-model",fetcher as typeof fetch);assert.deepEqual(await provider.embed(["a","b"]),[[1,2],[3,4]])});
