import { timingSafeEqual } from "node:crypto";
import { z } from "zod";
import type { ChannelConnector, ConnectorMessage } from "./types";
// Overridable for local end-to-end tests against a fake Bot API.
const telegramBase=()=>process.env.TELEGRAM_API_BASE??"https://api.telegram.org";
type TelegramConfig={botToken:string;webhookSecret:string};
const configSchema=z.object({botToken:z.string().regex(/^\d+:[A-Za-z0-9_-]{30,}$/),webhookSecret:z.string().min(16).max(256)});
export class TelegramConnector implements ChannelConnector<TelegramConfig>{readonly type="TELEGRAM";validateConfig(value:unknown){return configSchema.parse(value)}async verifyConnection(config:TelegramConfig){try{const response=await fetch(`${telegramBase()}/bot${config.botToken}/getMe`,{signal:AbortSignal.timeout(8000)});const body=await response.json() as {ok:boolean;result?:{id:number;username?:string};description?:string};return body.ok&&body.result?{ok:true,externalId:String(body.result.id),displayName:`@${body.result.username??body.result.id}`}:{ok:false,error:body.description??"Telegram отклонил токен"}}catch{return{ok:false,error:"Telegram временно недоступен"}}}verifyWebhook(_:string,headers:Headers,config:TelegramConfig){const actual=headers.get("x-telegram-bot-api-secret-token")??"";const a=Buffer.from(actual);const b=Buffer.from(config.webhookSecret);return a.length===b.length&&timingSafeEqual(a,b)}parseWebhook(payload:unknown){const parsed=z.object({update_id:z.number(),message:z.object({message_id:z.number(),date:z.number(),text:z.string().optional(),chat:z.object({id:z.union([z.string(),z.number()])}),from:z.object({id:z.number(),first_name:z.string().optional(),last_name:z.string().optional(),username:z.string().optional()}).optional()}).optional()}).safeParse(payload);if(!parsed.success||!parsed.data.message?.text)return[];const m=parsed.data.message;const raw=m.text;if(!raw)return[];
// "/start" (optionally with a deep-link payload) opens the chat; answer it as a greeting.
const text=/^\/start(\s|$)/.test(raw)?"Здравствуйте!":raw;return[{externalConversationId:String(m.chat.id),externalMessageId:String(m.message_id),senderId:String(m.from?.id??m.chat.id),senderName:[m.from?.first_name,m.from?.last_name].filter(Boolean).join(" ")||(m.from?.username?`@${m.from.username}`:undefined),text,receivedAt:new Date(m.date*1000)}] satisfies ConnectorMessage[]}async registerWebhook(config:TelegramConfig,url:string){const response=await fetch(`${telegramBase()}/bot${config.botToken}/setWebhook`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({url,secret_token:config.webhookSecret,allowed_updates:["message"],drop_pending_updates:false}),signal:AbortSignal.timeout(8000)});const body=await response.json() as {ok:boolean;description?:string};if(!body.ok)throw new Error(body.description??"Telegram setWebhook failed")}async unregisterWebhook(config:TelegramConfig){await fetch(`${telegramBase()}/bot${config.botToken}/deleteWebhook`,{method:"POST",signal:AbortSignal.timeout(8000)}).catch(()=>undefined)}async sendMessage(config:TelegramConfig,recipientId:string,text:string){const response=await fetch(`${telegramBase()}/bot${config.botToken}/sendMessage`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({chat_id:recipientId,text})});const body=await response.json() as {ok:boolean;result?:{message_id:number};description?:string};if(!body.ok||!body.result)throw new Error(body.description??"Telegram send failed");return{externalMessageId:String(body.result.message_id)}}}
