import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { getApiWorkspace } from "@/lib/auth/api";
import { encryptCredentials } from "@/lib/security/encryption";
import { getConnector, supportedConnectors } from "@/lib/connectors/registry";
const requestSchema=z.object({type:z.enum(["WEBSITE","TELEGRAM","WHATSAPP","EMAIL"]),employeeId:z.string().cuid(),config:z.record(z.unknown()).default({})});
export async function GET(){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const channels=await db.channel.findMany({where:{workspaceId:auth.workspaceId},include:{employee:{select:{id:true,name:true}}},orderBy:{createdAt:"asc"}});return NextResponse.json({channels:channels.map(({configEncrypted,...safe})=>safe),available:supportedConnectors})}
export async function POST(request:Request){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});if(!["OWNER","ADMIN"].includes(auth.membership.role))return NextResponse.json({error:"FORBIDDEN"},{status:403});const parsed=requestSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"INVALID_REQUEST",issues:parsed.error.flatten()},{status:400});const employee=await db.aIEmployee.findFirst({where:{id:parsed.data.employeeId,workspaceId:auth.workspaceId}});if(!employee)return NextResponse.json({error:"EMPLOYEE_NOT_FOUND"},{status:404});const connector=getConnector(parsed.data.type);let config;try{config=connector.validateConfig(parsed.data.config)}catch{return NextResponse.json({error:"INVALID_CREDENTIALS"},{status:400})}const check=await connector.verifyConnection(config);const channel=await db.channel.upsert({where:{workspaceId_type:{workspaceId:auth.workspaceId,type:parsed.data.type}},create:{workspaceId:auth.workspaceId,employeeId:employee.id,type:parsed.data.type,status:check.ok?"CONNECTED":"ERROR",configEncrypted:encryptCredentials(config),externalId:check.externalId,lastError:check.error},update:{employeeId:employee.id,status:check.ok?"CONNECTED":"ERROR",configEncrypted:encryptCredentials(config),externalId:check.externalId,lastError:check.error}});await db.auditLog.create({data:{workspaceId:auth.workspaceId,userId:auth.user.id,actorType:"USER",action:"CHANNEL_CONFIGURED",entityType:"Channel",entityId:channel.id,metadata:{type:channel.type,status:channel.status}}});return NextResponse.json({id:channel.id,type:channel.type,status:channel.status,displayName:check.displayName,error:check.error},{status:check.ok?201:422})}
