import { createHash, randomBytes } from "node:crypto";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { getApiWorkspace } from "@/lib/auth/api";
import { ResendEmailProvider } from "@/lib/email/provider";
import { createTranslator } from "@/lib/i18n";
const schema=z.object({email:z.string().trim().toLowerCase().email(),role:z.enum(["ADMIN","MANAGER","VIEWER"]).default("MANAGER")});
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
export async function GET(){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const [members,invitations]=await Promise.all([db.workspaceMember.findMany({where:{workspaceId:auth.workspaceId},include:{user:{select:{id:true,name:true,email:true}}},orderBy:{id:"asc"}}),db.workspaceInvitation.findMany({where:{workspaceId:auth.workspaceId,acceptedAt:null,expiresAt:{gt:new Date()}},select:{id:true,email:true,role:true,expiresAt:true,createdAt:true}})]);return NextResponse.json({members,invitations})}
export async function POST(request:Request){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});if(!["OWNER","ADMIN"].includes(auth.membership.role))return NextResponse.json({error:"FORBIDDEN"},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const t=createTranslator(auth.locale);const existing=await db.workspaceMember.findFirst({where:{workspaceId:auth.workspaceId,user:{email:parsed.data.email}}});if(existing)return NextResponse.json({error:"ALREADY_MEMBER"},{status:409});const token=randomBytes(32).toString("base64url");const invitation=await db.workspaceInvitation.upsert({where:{workspaceId_email:{workspaceId:auth.workspaceId,email:parsed.data.email}},create:{workspaceId:auth.workspaceId,email:parsed.data.email,role:parsed.data.role,tokenHash:hash(token),expiresAt:new Date(Date.now()+7*86400_000)},update:{role:parsed.data.role,tokenHash:hash(token),expiresAt:new Date(Date.now()+7*86400_000),acceptedAt:null}});const url=`${process.env.PUBLIC_APP_URL??"http://localhost:3000"}/invite/${token}?lang=${auth.locale}`;let delivery="SENT";try{await new ResendEmailProvider().send({to:parsed.data.email,subject:t("server.inviteSubject",{workspace:auth.membership.workspace.name}),html:`<p>${t("server.inviteBody")}</p><p><a href="${url}">${t("server.inviteCta")}</a></p><p>${t("server.inviteExpiry")}</p>`,idempotencyKey:`workspace-invite-${invitation.id}`})}catch{delivery="PROVIDER_NOT_CONFIGURED";await db.notification.create({data:{workspaceId:auth.workspaceId,type:"INTEGRATION",title:t("server.inviteFailedTitle"),body:t("server.inviteFailedBody")}})}await db.auditLog.create({data:{workspaceId:auth.workspaceId,userId:auth.user.id,actorType:"USER",action:"MEMBER_INVITED",entityType:"WorkspaceInvitation",entityId:invitation.id,metadata:{email:parsed.data.email,role:parsed.data.role,delivery}}});return NextResponse.json({id:invitation.id,email:invitation.email,role:invitation.role,delivery,...(process.env.NODE_ENV!=="production"?{developmentInviteUrl:url}:{})},{status:201})}
