import type { Locale } from "@/lib/i18n";

export const landingCopy = {
  ru: {
    nav: { features: "Возможности", how: "Как работает", roles: "Роли", pricing: "Тарифы", faq: "Вопросы", login: "Войти", start: "Начать бесплатно", cabinet: "Открыть кабинет" },
    hero: {
      pill: "AI-сотрудник для бизнеса",
      titleA: "Наймите сотрудника, который",
      titleAccent: "не пропускает",
      titleB: "ни одного клиента",
      copy: "Lemiri отвечает клиентам, собирает заявки, записывает на услуги и передаёт сложные диалоги команде — по правилам вашего бизнеса.",
      primary: "Создать AI-сотрудника",
      secondary: "Как это работает",
      note: "14 дней бесплатно · без карты · запуск за 15 минут",
    },
    float: { lead: "Лид квалифицирован", leadMeta: "Бюджет подтверждён", crm: "Отправлено в CRM", crmMeta: "Webhook · 0,4 с", slots: "Свободные окна", slotsMeta: "Сегодня" },
    channelsTitle: "Работает там, где уже пишут ваши клиенты",
    channels: ["Сайт", "WhatsApp", "Telegram", "Календарь", "CRM", "Email"],
    features: {
      kicker: "Возможности",
      title: "Не чат-бот. Сотрудник, который доводит дело до конца",
      copy: "Lemiri понимает контекст, работает по вашим знаниям и выполняет действия в ваших системах — только те, что вы разрешили.",
      items: [
        { title: "Общение", copy: "Ведёт естественный диалог в чате и мессенджерах, сохраняя тон вашего бренда." },
        { title: "Знания", copy: "Отвечает по сайту, документам, FAQ и правилам компании — и показывает, откуда взял ответ." },
        { title: "Контроль", copy: "Замечает сложные вопросы и передаёт диалог человеку с готовым кратким резюме." },
        { title: "Действия", copy: "Создаёт лиды, предлагает свободное время, обновляет статусы и уведомляет команду." },
      ],
    },
    how: {
      kicker: "Как работает",
      titleA: "От идеи до первого",
      titleAccent: "диалога за 15 минут",
      copy: "Никакого кода. Вы настраиваете сотрудника так же, как вводите в работу нового человека.",
      steps: [
        { title: "Выберите роль", copy: "Администратор, продажи или поддержка — шаблон задаст стартовую логику." },
        { title: "Добавьте знания", copy: "Сайт, прайс, документы и ответы на частые вопросы. Индексация — автоматически." },
        { title: "Подключите каналы", copy: "Виджет на сайт, Telegram, WhatsApp, email. Ключи шифруются." },
        { title: "Проверьте и запустите", copy: "Поговорите с сотрудником как клиент. Публикация — после успешного теста." },
      ],
    },
    roles: {
      kicker: "Роли",
      title: "Готовые роли под ваши задачи",
      pick: "Выбрать роль",
      items: [
        { title: "Администратор", copy: "Отвечает на вопросы, записывает на услуги и напоминает о визите.", tags: ["Запись", "Напоминания", "Цены"] },
        { title: "Менеджер продаж", copy: "Выясняет потребность, уточняет бюджет и передаёт квалифицированный лид.", tags: ["Квалификация", "CRM", "Лиды"] },
        { title: "Поддержка", copy: "Закрывает типовые обращения и вовремя подключает человека.", tags: ["FAQ", "Эскалация", "Резюме"] },
      ],
    },
    analytics: {
      kicker: "Результаты",
      title: "Видно, что сотрудник приносит бизнесу",
      copy: "Каждый диалог, лид и запись — в одной панели. Lemiri сам подсказывает, каких знаний ему не хватает.",
      period: "Неделя · 1–7 августа",
      metrics: [
        { label: "Сообщений", value: 846, delta: "+18%" },
        { label: "Лидов", value: 127, delta: "+31%" },
        { label: "Записей", value: 64, delta: "+12%" },
      ],
      days: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
      insight: "7 клиентов спросили о рассрочке — добавьте условия в базу знаний",
    },
    pricing: {
      kicker: "Тарифы",
      title: "Начните бесплатно, растите без сюрпризов",
      recommended: "Популярный",
      choose: "Выбрать",
      contact: "Связаться",
      plans: [
        { name: "Free", price: "$0", period: "14 дней", copy: "Тест AI-сотрудника, чат на сайте, ограниченный объём сообщений." },
        { name: "Starter", price: "$19", period: "в месяц", copy: "1 AI-сотрудник, сайт + Telegram, база знаний, лиды и базовая аналитика." },
        { name: "Pro", price: "$49", period: "в месяц", copy: "WhatsApp, Telegram, сайт, CRM, календарь, автоматические действия, больше лимитов." },
        { name: "Business", price: "$99", period: "в месяц", copy: "Несколько AI-сотрудников, расширенная аналитика, интеграции и приоритетная поддержка." },
        { name: "Enterprise", price: "Индивидуально", period: "", copy: "Кастомные интеграции, SLA и отдельные условия для больших объёмов." },
      ],
    },
    faq: {
      kicker: "Вопросы",
      title: "Частые вопросы",
      items: [
        { q: "ИИ может ошибиться?", a: "Сотрудник отвечает только по подключённым источникам и показывает, откуда взял ответ. Если уверенности мало — передаёт диалог человеку." },
        { q: "Нужно уметь программировать?", a: "Нет. Настройка идёт по шагам, как ввод нового сотрудника: роль, знания, канал, тест." },
        { q: "Можно подключить CRM?", a: "Да. Лиды и записи уходят в CRM через подписанные webhooks, а популярные системы подключаются напрямую." },
        { q: "Что происходит, когда нужен человек?", a: "Lemiri передаёт диалог по вашим правилам вместе с кратким резюме — менеджер продолжает с того же места." },
        { q: "Где хранятся данные?", a: "Данные изолированы по рабочим пространствам, ключи подключений шифруются, срок хранения вы выбираете сами." },
      ],
    },
    cta: { title: "Первый AI-сотрудник выйдет на смену сегодня", copy: "Запуск за 15 минут. 14 дней бесплатно, без привязки карты.", primary: "Начать бесплатно", secondary: "Запросить демо" },
    footer: { rights: "© 2026 Lemiri AI", made: "Сделано для бизнеса, который ценит каждого клиента" },
  },
  en: {
    nav: { features: "Features", how: "How it works", roles: "Roles", pricing: "Pricing", faq: "FAQ", login: "Sign in", start: "Start free", cabinet: "Open dashboard" },
    hero: {
      pill: "AI employee for business",
      titleA: "Hire an employee who",
      titleAccent: "never misses",
      titleB: "a single customer",
      copy: "Lemiri answers customers, collects requests, books appointments and hands complex conversations to your team — following your business rules.",
      primary: "Create an AI employee",
      secondary: "How it works",
      note: "14 days free · no card · live in 15 minutes",
    },
    float: { lead: "Lead qualified", leadMeta: "Budget confirmed", crm: "Sent to CRM", crmMeta: "Webhook · 0.4 s", slots: "Open slots", slotsMeta: "Today" },
    channelsTitle: "Works where your customers already write",
    channels: ["Website", "WhatsApp", "Telegram", "Calendar", "CRM", "Email"],
    features: {
      kicker: "Features",
      title: "Not a chatbot. An employee who gets things done",
      copy: "Lemiri understands context, answers from your knowledge and takes actions in your systems — only the ones you allow.",
      items: [
        { title: "Conversation", copy: "Holds natural conversations in chat and messengers in your brand's voice." },
        { title: "Knowledge", copy: "Answers from your website, documents, FAQ and policies — and shows where the answer came from." },
        { title: "Control", copy: "Spots complex questions and hands the conversation to a person with a ready summary." },
        { title: "Actions", copy: "Creates leads, offers open slots, updates statuses and notifies the team." },
      ],
    },
    how: {
      kicker: "How it works",
      titleA: "From idea to the first",
      titleAccent: "conversation in 15 minutes",
      copy: "No code. You set up the employee the same way you onboard a new hire.",
      steps: [
        { title: "Pick a role", copy: "Front desk, sales or support — the template sets the starting logic." },
        { title: "Add knowledge", copy: "Website, prices, documents and FAQs. Indexing is automatic." },
        { title: "Connect channels", copy: "Website widget, Telegram, WhatsApp, email. Keys are encrypted." },
        { title: "Test and launch", copy: "Talk to the employee as a customer. Publish after a passing test." },
      ],
    },
    roles: {
      kicker: "Roles",
      title: "Ready-made roles for your goals",
      pick: "Choose role",
      items: [
        { title: "Front desk", copy: "Answers questions, books services and sends visit reminders.", tags: ["Booking", "Reminders", "Prices"] },
        { title: "Sales manager", copy: "Uncovers needs, clarifies budget and hands over a qualified lead.", tags: ["Qualification", "CRM", "Leads"] },
        { title: "Support", copy: "Resolves routine requests and brings in a person at the right time.", tags: ["FAQ", "Escalation", "Summary"] },
      ],
    },
    analytics: {
      kicker: "Results",
      title: "See what your employee brings the business",
      copy: "Every conversation, lead and booking in one view. Lemiri even tells you which knowledge it is missing.",
      period: "Week · Aug 1–7",
      metrics: [
        { label: "Messages", value: 846, delta: "+18%" },
        { label: "Leads", value: 127, delta: "+31%" },
        { label: "Bookings", value: 64, delta: "+12%" },
      ],
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      insight: "7 customers asked about installments — add the terms to your knowledge base",
    },
    pricing: {
      kicker: "Pricing",
      title: "Start free, grow without surprises",
      recommended: "Popular",
      choose: "Choose",
      contact: "Contact us",
      plans: [
        { name: "Free", price: "$0", period: "14 days", copy: "AI employee test, website chat and limited messages." },
        { name: "Starter", price: "$19", period: "per month", copy: "1 AI employee, website + Telegram, knowledge base, leads and basic analytics." },
        { name: "Pro", price: "$49", period: "per month", copy: "WhatsApp, Telegram, website, CRM, calendar, automations and higher limits." },
        { name: "Business", price: "$99", period: "per month", copy: "Several AI employees, advanced analytics, integrations and priority support." },
        { name: "Enterprise", price: "Custom", period: "", copy: "Custom integrations, SLA and individual terms for high volumes." },
      ],
    },
    faq: {
      kicker: "FAQ",
      title: "Frequently asked questions",
      items: [
        { q: "Can the AI make mistakes?", a: "The employee answers only from connected sources and shows where each answer came from. When confidence is low, it hands the conversation to a person." },
        { q: "Do I need to code?", a: "No. Setup is step by step, like onboarding a new hire: role, knowledge, channel, test." },
        { q: "Can I connect my CRM?", a: "Yes. Leads and bookings are delivered via signed webhooks, and popular CRMs connect directly." },
        { q: "What happens when a human is needed?", a: "Lemiri hands over by your rules together with a short summary, so your manager continues from the same point." },
        { q: "Where is the data stored?", a: "Data is isolated per workspace, connection keys are encrypted and you choose the retention period." },
      ],
    },
    cta: { title: "Your first AI employee can start today", copy: "Live in 15 minutes. 14 days free, no card required.", primary: "Start free", secondary: "Request a demo" },
    footer: { rights: "© 2026 Lemiri AI", made: "Built for businesses that value every customer" },
  },
} as const;

export type LandingCopy = (typeof landingCopy)[Locale];
