import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { decryptCredentials } from "@/lib/security/encryption";
import { getConnector } from "@/lib/connectors/registry";
import { ingestConnectorMessage } from "@/lib/connectors/ingest";
import type { WhatsAppConfig } from "@/lib/connectors/whatsapp";

export async function GET(request:Request,{params}:{params:Promise<{type:string;channelId:string}>}){const {type,channelId}=await params;if(type.toUpperCase()!=="WHATSAPP")return NextResponse.json({error:"METHOD_NOT_SUPPORTED"},{status:405});const channel=await db.channel.findFirst({where:{id:channelId,type:"WHATSAPP",status:"CONNECTED"}});if(!channel?.configEncrypted)return NextResponse.json({error:"CHANNEL_NOT_FOUND"},{status:404});const config=decryptCredentials<WhatsAppConfig>(channel.configEncrypted);const url=new URL(request.url);const mode=url.searchParams.get("hub.mode");const token=url.searchParams.get("hub.verify_token");const challenge=url.searchParams.get("hub.challenge");if(mode!=="subscribe"||token!==config.verifyToken||!challenge)return NextResponse.json({error:"VERIFICATION_FAILED"},{status:403});return new NextResponse(challenge,{headers:{"content-type":"text/plain"}})}

export async function POST(request:Request,{params}:{params:Promise<{type:string;channelId:string}>}){const {type,channelId}=await params;const channel=await db.channel.findFirst({where:{id:channelId,type:type.toUpperCase(),status:"CONNECTED"}});if(!channel?.configEncrypted)return NextResponse.json({error:"CHANNEL_NOT_FOUND"},{status:404});const raw=await request.text();const connector=getConnector(channel.type);const config=decryptCredentials<Record<string,string>>(channel.configEncrypted);if(!connector.verifyWebhook(raw,request.headers,config))return NextResponse.json({error:"INVALID_SIGNATURE"},{status:401});let payload:unknown;try{payload=JSON.parse(raw)}catch{return NextResponse.json({error:"INVALID_JSON"},{status:400})}const messages=connector.parseWebhook(payload);const results=[];for(const message of messages)results.push(await ingestConnectorMessage(channel,message));return NextResponse.json({ok:true,processed:results.length,results})}
