import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { getApiWorkspace } from "@/lib/auth/api";
import { getDirectWorkspaceSettings } from "@/lib/neon-direct";
const time=z.string().regex(/^(?:[01]\d|2[0-3]):[0-5]\d$/);
const schema=z.object({name:z.string().trim().min(2).max(120).optional(),locale:z.enum(["ru","en"]).optional(),timezone:z.string().min(3).max(80).optional(),dataRetentionDays:z.number().int().min(30).max(3650).optional(),analyticsEnabled:z.boolean().optional(),aiTrainingOptIn:z.boolean().optional(),theme:z.enum(["system","light","dark"]).optional(),logoUrl:z.string().max(2_100_000).refine(value=>value===""||value.startsWith("data:image/")||z.string().url().safeParse(value).success,"INVALID_LOGO").optional().transform(value=>value||null),workingHours:z.object({days:z.array(z.number().int().min(0).max(6)).min(1).max(7),start:time,end:time}).refine(value=>value.start<value.end,{message:"END_MUST_BE_AFTER_START"}).optional()});
export async function GET(){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const settings=process.env.NODE_ENV==="production"?await getDirectWorkspaceSettings(auth.workspaceId):await db.workspaceSettings.upsert({where:{workspaceId:auth.workspaceId},create:{workspaceId:auth.workspaceId},update:{}});return NextResponse.json({workspace:{id:auth.membership.workspace.id,name:auth.membership.workspace.name,slug:auth.membership.workspace.slug},settings})}
export async function PATCH(request:Request){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});if(!["OWNER","ADMIN"].includes(auth.membership.role))return NextResponse.json({error:"FORBIDDEN"},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"INVALID_REQUEST",issues:parsed.error.flatten()},{status:400});const {name,...settings}=parsed.data;const result=await db.$transaction(async tx=>{if(name)await tx.workspace.update({where:{id:auth.workspaceId},data:{name}});return tx.workspaceSettings.upsert({where:{workspaceId:auth.workspaceId},create:{workspaceId:auth.workspaceId,...settings},update:settings})});await db.auditLog.create({data:{workspaceId:auth.workspaceId,userId:auth.user.id,actorType:"USER",action:"WORKSPACE_SETTINGS_UPDATED",entityType:"Workspace",entityId:auth.workspaceId,metadata:{fields:Object.keys(parsed.data)}}});return NextResponse.json(result)}
