import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { getApiWorkspace } from "@/lib/auth/api";
import { getConnector } from "@/lib/connectors/registry";
import { decryptCredentials, encryptCredentials } from "@/lib/security/encryption";
import { normalizeOrigins, normalizeWidgetSettings, type WebsiteChannelConfig } from "@/lib/widget/settings";
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});if(!["OWNER","ADMIN"].includes(auth.membership.role))return NextResponse.json({error:"FORBIDDEN"},{status:403});const {id}=await params;const existing=await db.channel.findFirst({where:{id,workspaceId:auth.workspaceId},select:{type:true,configEncrypted:true}});if(existing?.configEncrypted){const connector=getConnector(existing.type);if(connector.unregisterWebhook)await connector.unregisterWebhook(decryptCredentials(existing.configEncrypted)).catch(()=>undefined)}const updated=await db.channel.updateMany({where:{id,workspaceId:auth.workspaceId},data:{status:"DISCONNECTED",configEncrypted:null,externalId:null}});if(!updated.count)return NextResponse.json({error:"NOT_FOUND"},{status:404});await db.auditLog.create({data:{workspaceId:auth.workspaceId,userId:auth.user.id,actorType:"USER",action:"CHANNEL_DISCONNECTED",entityType:"Channel",entityId:id}});return new NextResponse(null,{status:204})}

// Website widget: appearance, allowed sites and where the widget was seen.
async function websiteChannel(id:string,workspaceId:string){return db.channel.findFirst({where:{id,workspaceId,type:"WEBSITE"},select:{id:true,employeeId:true,status:true,configEncrypted:true}})}
const readConfig=(packed:string|null):WebsiteChannelConfig=>{if(!packed)return{allowedOrigins:[]};try{const value=decryptCredentials<WebsiteChannelConfig>(packed);return{...value,allowedOrigins:value.allowedOrigins??[]}}catch{return{allowedOrigins:[]}}};
const view=(config:WebsiteChannelConfig)=>({widget:config.widget??{},allowedOrigins:config.allowedOrigins,seen:Object.entries(config.seen??{}).map(([origin,at])=>({origin,lastSeenAt:new Date(at).toISOString()})).sort((a,b)=>b.lastSeenAt.localeCompare(a.lastSeenAt))});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const {id}=await params;const channel=await websiteChannel(id,auth.workspaceId);if(!channel)return NextResponse.json({error:"NOT_FOUND"},{status:404});return NextResponse.json({id:channel.id,employeeId:channel.employeeId,status:channel.status,...view(readConfig(channel.configEncrypted))},{headers:{"cache-control":"no-store"}})}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await getApiWorkspace();if(!auth)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});if(!["OWNER","ADMIN"].includes(auth.membership.role))return NextResponse.json({error:"FORBIDDEN"},{status:403});const {id}=await params;const channel=await websiteChannel(id,auth.workspaceId);if(!channel)return NextResponse.json({error:"NOT_FOUND"},{status:404});const body=await request.json().catch(()=>null) as {widget?:unknown;allowedOrigins?:unknown}|null;if(!body)return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const config=readConfig(channel.configEncrypted);if(body.widget!==undefined)config.widget=normalizeWidgetSettings(body.widget);if(body.allowedOrigins!==undefined)config.allowedOrigins=normalizeOrigins(body.allowedOrigins);await db.channel.update({where:{id:channel.id},data:{configEncrypted:encryptCredentials(config)}});await db.auditLog.create({data:{workspaceId:auth.workspaceId,userId:auth.user.id,actorType:"USER",action:"CHANNEL_CONFIGURED",entityType:"Channel",entityId:channel.id,metadata:{type:"WEBSITE",widget:true}}});return NextResponse.json(view(config))}
